language: java

cache:
  directories:
  - $HOME/.m2

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - test "$TRAVIS_COVERALLS" == "true" && mvn clean test jacoco:report
after_success:
  - test "$TRAVIS_COVERALLS" == "true" && test "$TRAVIS_PULL_REQUEST" == "false" && mvn coveralls:report -DrepoToken=$REPO_TOKEN
