language: java

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
jdk:
  - openjdk12
  - openjdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
after_success:
  - test "$TRAVIS_JDK_VERSION" == "oraclejdk8" && mvn clean test jacoco:report coveralls:report